# Define the environment 
name: Go project test 

# Set the workflow to run on push, pull_request events that target the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  
  # Manually run a workflow by configuring the workflow to use the workflow_dispatch event 
  workflow_dispatch:
    branches: [ master ]
    
jobs:
  build:
    # Set the operating system 
    name: Build
    runs-on: macos-latest
    steps:
    # Set up Go
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15.2
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    # Set up dependencies 
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    # Define how to build 
    - name: Build
      run: go build -v .
    # Run automated tests 
    - name: Test
      run: go test -v .
